name: Build Container Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR merge event or commit message
        if: github.event_name == 'pull_request' || contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')
        run: |
          docker build -t your-image .
          docker push your-image
